<?php

/**
 * @file
 * Functions to support theming.
 */

use Drupal\Component\Utility\Crypt;
use Drupal\Core\Render\Element;
use Drupal\image\Entity\ImageStyle;

/**
 * Set theme CSS on top of all other CSS files.
 */
function base_theme_css_alter(&$css, $assets) {
  $base_css = \Drupal::service('extension.list.theme')->getPath('base_theme') . '/dist/css/styles.css';

  if (isset($css[$base_css])) {
    $css[$base_css]['group'] = 300;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess(&$variables, $hook) {
  $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
  $variables['site_settings'] = \Drupal::config('system.site');
  $variables['base_settings'] = \Drupal::entityTypeManager()->getStorage('config_pages')->load('settings');

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $variables['content_type'] = $node->bundle();
  }

  if (isset($variables['elements']['#tag'])) {
    $variables['tag'] = $variables['elements']['#tag'];
  }
  if (isset($variables['element']['#tag'])) {
    $variables['tag'] = $variables['element']['#tag'];
  }

}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess_page(&$variables) {
  $variables['search_id'] = 'search_api_page_block_form_default_search_page';
  $variables['search_build_id'] = 'form-' . Crypt::randomBytesBase64();
  $variables['search_token'] = \Drupal::csrfToken()->get('form_token_placeholder_' . Crypt::hashBase64($variables['search_id']));
}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess_node(&$variables) {
  if (isset($variables['content']['title']['#access'])) {
    $variables['content']['title']['#access'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess_menu(&$variables) {
  $variables['search_id'] = 'search_api_page_block_form_default_search_page';
  $variables['search_build_id'] = 'form-' . Crypt::randomBytesBase64();
  $variables['search_token'] = \Drupal::csrfToken()->get('form_token_placeholder_' . Crypt::hashBase64($variables['search_id']));
}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess_symfony_mailer_lite_email(&$variables) {
  $default_theme = \Drupal::config('system.theme')->get('default');
  $variables['site_logo'] = theme_get_setting('logo.url', $default_theme);
  $variables['site_name'] = \Drupal::config('system.site')->get('name');
  $variables['bg_color'] = '#F1F1F1';
  $variables['bg_font_color'] = '#2B2D42';
  $variables['fg_color'] = '#FFFFFF';
  $variables['fg_font_color'] = '#414142';
  $variables['font_family'] = 'Tahoma, Geneva, sans-serif';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess_form(&$variables) {
  $request = \Drupal::request();
  $route_match = \Drupal::routeMatch();
  $variables['page_title'] = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess_field(&$variables) {
  if (isset($variables['element']['#tag'])) {
    $variables['tag'] = $variables['element']['#tag'];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess_media(&$variables) {
  if ($variables['media']->bundle() === 'image') {
    if (isset($variables['content']['field_media_images'])) {
      $variables['content']['field_media_images']['#access'] = FALSE;
    }

    $srcset = [];
    $sources = [];

    foreach ($variables['media']->field_media_images as $key => $image) {
      $dimensions = ['width' => $image->width, 'height' => $image->height];
      $image_uri = $image->entity->getFileUri();
      $image_url = \Drupal::service('file_url_generator')->generateAbsoluteString($image_uri);

      if (!empty($variables['content']['field_media_images'][$key]['#image_style'])) {
        $image_style = ImageStyle::load($variables['content']['field_media_images'][$key]['#image_style']);
        $image_style->transformDimensions($dimensions, $image_uri);
        if ($image_style->supportsUri($image_uri)) {
          $image_url = $image_style->buildUrl($image_uri);
        }
      }

      $srcset[] = $image_url . ' ' . $dimensions['width'] . 'w';
      $sources[] = [
        'srcset' => $image_url,
        'media' => $dimensions['width'],
      ];
    }

    $image = $variables['media']->field_media_image;
    $dimensions = ['width' => $image->width, 'height' => $image->height];
    $image_uri = $image->entity->getFileUri();
    $image_url = \Drupal::service('file_url_generator')->generateAbsoluteString($image_uri);

    if (!empty($variables['content']['field_media_image'][0]['#image_style'])) {
      $image_style = ImageStyle::load($variables['content']['field_media_image'][0]['#image_style']);
      $image_style->transformDimensions($dimensions, $image_uri);
      if ($image_style->supportsUri($image_uri)) {
        $image_url = $image_style->buildUrl($image_uri);
      }
    }

    $srcset[] = $image_url . ' ' . $dimensions['width'] . 'w';
    $sources[] = [
      'srcset' => $image_url,
      'media' => $dimensions['width'],
    ];

    array_multisort(array_column($sources, 'media'), $sources);

    if (count($srcset) > 1) {
      //$variables['content']['field_media_image'][0]['#item_attributes']['srcset'] = implode(', ', $srcset);
      $variables['content']['field_media_image'][0]['#item_attributes']['width'] = '';
      $variables['content']['field_media_image'][0]['#item_attributes']['height'] = '';
      $variables['elements']['#sources'] = $sources;
    }
  }
}

/**
 * Implements hook_preprocess_image_widget().
 */
function base_theme_preprocess_image_widget(array &$variables): void {
  $data = &$variables['data'];

  // This prevents image widget templates from rendering preview container HTML
  // to users that do not have permission to access these previews.
  // @todo revisit in https://drupal.org/node/953034
  // @todo revisit in https://drupal.org/node/3114318
  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function base_theme_preprocess_file_video(&$variables) {
  if (isset($variables['attributes']['width']) && $variables['attributes']['width']->value() == 0) {
    $variables['attributes']->removeAttribute('width');
  }
  if (isset($variables['attributes']['height']) && $variables['attributes']['height']->value() == 0) {
    $variables['attributes']->removeAttribute('height');
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function base_theme_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['breadcrumb'])) {
    if ($key = array_search('gin_preprocess_breadcrumb', $theme_registry['breadcrumb']['preprocess functions'])) {
      unset($theme_registry['breadcrumb']['preprocess functions'][$key]);
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function base_theme_theme_suggestions_page_alter(&$suggestions, array $variables) {
  if (isset($variables['content_type'])) {
    $suggestions[] = $variables['theme_hook_original'] . '__node__' . $variables['content_type'];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function base_theme_theme_suggestions_container_alter(&$suggestions, array &$variables) {
  $type = $name = $display = '';

  if (empty($suggestions) && isset($variables['element']['#type']) && $variables['element']['#type'] !== 'container') {

    $type = $variables['element']['#type'];
    if (!array_search($variables['theme_hook_original'] . '__' . $type, $suggestions)) {
      $suggestions[] = $variables['theme_hook_original'] . '__' . $type;
    }

    if (isset($variables['element']['#name'])) {
      $name = $variables['element']['#name'];
      $suggestions[] = $variables['theme_hook_original'] . '__' . $type . '__' . $name;

      if (isset($variables['element']['#view_display_plugin_id'])) {
        $display = $variables['element']['#view_display_plugin_id'];
        $suggestions[] = $variables['theme_hook_original'] . '__' . $type . '__' . $name . '__' . $display;
      }
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function base_theme_theme_suggestions_form_alter(&$suggestions, array &$variables) {
  foreach (array_reverse($variables['element']['#theme']) as $theme) {
    array_unshift($suggestions, 'form__' . $theme);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function base_theme_theme_suggestions_input_alter(&$suggestions, array $variables) {
  $element = $variables['element'];

  if (isset($element['#attributes']['data-twig-suggestion'])) {
    $suggestions[] = 'input__' . $element['#type'] . '__' . $element['#attributes']['data-twig-suggestion'];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function base_theme_theme_suggestions_bef_links_alter(&$suggestions, array &$variables) {
  if (isset($variables['element']['#context']['#view_id'])) {
    $suggestions[] = $variables['theme_hook_original'] . '__' . $variables['element']['#context']['#view_id'];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function base_theme_theme_suggestions_field_alter(&$suggestions, array &$variables) {
  $base = $variables['theme_hook_original'] . '__' . $variables['element']['#entity_type'];
  $bundle = $base . '__' . $variables['element']['#bundle'];
  $new = $bundle . '__' . $variables['element']['#view_mode'];
  if ($key = array_search($bundle, $suggestions)) {
    array_splice($suggestions, ++$key, 0, $new);
  }
  else {
    $suggestions[] = $new;
  }
  $suggestions[] = $base . '__' . $variables['element']['#field_name'] . '__' . $variables['element']['#bundle'] . '__' . $variables['element']['#view_mode'];
}
